version: '3.5'

services:
  app:
    container_name: ${APP_ID}
    image: ${APP_ID}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/dist
      - /app/node_modules
    networks:
      - lumyri-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  postgres:
    image: postgres:14.4-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB_MAIN: ${DB_MAIN}
      # POSTGRES_DB_TEST: ${DB_TEST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - lumyri-network

networks:
  lumyri-network:
