version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - lumyri-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:14.4-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB_MAIN: ${DB_MAIN}
      # POSTGRES_DB_TEST: ${DB_TEST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - lumyri-network

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - lumyri-network

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   restart: unless-stopped
  #   environment:
  #     - REDIS_HOSTS=redis
  #   ports:
  #     - ${REDIS_COMMAND_PORT:-8081}:8081
  #   networks:
  #     - lumyri-network

  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    volumes:
      - ./minio:/data
    networks:
      - lumyri-network
networks:
  lumyri-network:
